//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestLibTravian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestLibTravian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;lmid1&quot;&gt;&lt;div id=&quot;lmid2&quot;&gt;&lt;h1&gt;&lt;b&gt;市场 等级 20&lt;/b&gt;&lt;/h1&gt;
        ///&lt;script language=&quot;JavaScript&quot;&gt;var summe=1328651;var max123=560000;var max4=560000;&lt;/script&gt;&lt;p&gt;
        ///&lt;table cellspacing=&quot;1&quot; cellpadding=&quot;2&quot; class=&quot;tbg&quot;&gt;
        ///&lt;form method=&quot;POST&quot; name=&quot;snd&quot; action=&quot;build.php&quot;&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;id&quot; value=&quot;38&quot;&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;t&quot; value=&quot;3&quot;&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;a&quot; value=&quot;6&quot;&gt;
        ///&lt;tr class=&quot;rbg&quot;&gt;
        ///&lt;td colspan=&quot;5&quot;&gt;和电脑商人交易&lt;/td&gt;
        ///&lt;/tr&gt;&lt;tr class=&quot;cbg1&quot;&gt;&lt;td width=&quot;20%&quot;&gt;&lt;a href=&quot;javascript:fillup(0);&quot;&gt;&lt;img sr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NPCTradeForm {
            get {
                return ResourceManager.GetString("NPCTradeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;&lt;/div&gt;&lt;div id=&quot;lmid1&quot;&gt;&lt;div id=&quot;lmid2&quot;&gt;&lt;h1&gt;&lt;b&gt;市场 等级 20&lt;/b&gt;&lt;/h1&gt;
        ///&lt;p&gt;你刚刚用&lt;img class=&quot;res&quot; src=&quot;img/un/r/1.gif&quot;&gt;&lt;b&gt;0&lt;/b&gt;木材、&lt;img class=&quot;res&quot; src=&quot;img/un/r/2.gif&quot;&gt;&lt;b&gt;0&lt;/b&gt;泥土、&lt;img class=&quot;res&quot; src=&quot;img/un/r/3.gif&quot;&gt;&lt;b&gt;0&lt;/b&gt;铁块和&lt;img class=&quot;res&quot; src=&quot;img/un/r/4.gif&quot;&gt;&lt;b&gt;559328&lt;/b&gt;粮食交换了&lt;img class=&quot;res&quot; src=&quot;img/un/r/1.gif&quot;&gt;&lt;b&gt;172652&lt;/b&gt;木材、&lt;img class=&quot;res&quot; src=&quot;img/un/r/2.gif&quot;&gt;&lt;b&gt;209476&lt;/b&gt;泥土、&lt;img class=&quot;res&quot; src=&quot;img/un/r/3.gif&quot;&gt;&lt;b&gt;177200&lt;/b&gt;铁块和&lt;img class=&quot;res&quot; src=&quot;img/un/r/4.gif&quot;&gt;&lt;b&gt;0&lt;/b&gt;粮食。这次交易花了你&lt;b&gt;3&lt;/b&gt;数量单位 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NPCTradeResult {
            get {
                return ResourceManager.GetString("NPCTradeResult", resourceCulture);
            }
        }
    }
}
